formatter: "markdown table" # this is required

version: ""

# header-from: ""
#footer-from: ""

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->